# Generated by Django 4.2.6 on 2023-10-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='publish_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
