# Generated by Django 4.2.6 on 2023-10-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=30)),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('button_label', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
