# Generated by Django 4.2.6 on 2023-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
