# Generated by Django 4.2.6 on 2023-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_icon_contact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.ImageField(upload_to='images/icons/'),
        ),
    ]
